[package]
name = "shtml"
version = "0.0.0"
authors = ["nullambs <null@ambs.cc>"]
description = "CSS-i[SH] H[TML]"
license = "MIT/Apache-2.0"
repository = "https://github.com/nullambs/shtml"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pest = "2.8.4"
pest_derive = "2.8.4"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3.55"

[dependencies.web-sys]
version = "0.3.82"
features = [ "console", "Document", "HtmlElement", "Window", "Text", "NodeList" ]

[package.metadata.wasm-pack.profile.release]
wasm-opt = [
  "-O4", "-Oz" 
]
